tests: select testdb and use MySQL 8.0 by default
Without the `USE...` in `TestExecuteMultiple` the test panics as the
result in `conn_test.go:108` is nil.

```
$ go test

----------------------------------------------------------------------
PANIC: conn_test.go:92: connTestSuite.TestExecuteMultiple

... Panic: runtime error: invalid memory address or nil pointer dereference (PC=0x438592)

/usr/lib/golang/src/runtime/panic.go:884
  in gopanic
/usr/lib/golang/src/runtime/panic.go:260
  in panicmem
/usr/lib/golang/src/runtime/signal_unix.go:837
  in sigpanic
conn_test.go:108
  in connTestSuite.TestExecuteMultiple.func1
conn.go:273
  in Conn.ExecuteMultiple
conn_test.go:101
  in connTestSuite.TestExecuteMultiple
/usr/lib/golang/src/reflect/value.go:370
  in Value.Call
/home/dvaneeden/go/pkg/mod/github.com/pingcap/check@v0.0.0-20190102082844-67f458068fc8/check.go:836
  in suiteRunner.forkTest.func1
/home/dvaneeden/go/pkg/mod/github.com/pingcap/check@v0.0.0-20190102082844-67f458068fc8/check.go:730
  in suiteRunner.forkCall.func1
/usr/lib/golang/src/runtime/asm_amd64.s:1598
  in goexit

----------------------------------------------------------------------
FAIL: conn_test.go:132: connTestSuite.TestExecuteSelectStreaming

conn_test.go:170:
    c.Assert(err, IsNil)
... value *mysql.MyError = &mysql.MyError{Code:0x416, Message:"No database selected", State:"3D000"} ("ERROR 1046 (3D000): No database selected")

----------------------------------------------------------------------
FAIL: conn_test.go:86: connTestSuite.TestFieldList

conn_test.go:88:
    c.Assert(err, IsNil)
... value *mysql.MyError = &mysql.MyError{Code:0x416, Message:"No database selected", State:"3D000"} ("ERROR 1046 (3D000): No database selected")

----------------------------------------------------------------------
FAIL: conn_test.go:38: connTestSuite.TearDownSuite

conn_test.go:43:
    s.testExecute_DropTable(c)
conn_test.go:83:
    c.Assert(err, IsNil)
... value *mysql.MyError = &mysql.MyError{Code:0x416, Message:"No database selected", State:"3D000"} ("ERROR 1046 (3D000): No database selected")

OOPS: 18 passed, 3 FAILED, 1 PANICKED
--- FAIL: Test (0.46s)
FAIL
exit status 1
FAIL	github.com/go-mysql-org/go-mysql/client	0.465s
```